[tool.poetry]
name = "mldevops-exercise"
version = "0.1.0"
description = ""
authors = ["Tomasz Turek <t.turek2000@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
